apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      appName: {{ .Values.appName }}
  template:
    metadata:
      labels:
        appName: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
